### ISSUE TITLE
Mettre à jour des informations (en commentaire)

### ISSUE THREAD

**Issue by ghost** [CLICGameStar/icelan-website-archive#13]
1. Dans la page "infos & planning" : supprimer la partie qui stipule la possibilité de payement sur place.
2. "nourriture et boissons" : quantitéS suffisantes ou alors quantité suffisante(s) (sans s)
3. dans les modalités des tournois il y 'a tantôt des":" tantôt des "=" --> en choisir et laisser qu'un si possible
4. toujours dans mod. tournois : remplacer le "blablabla" du jeu mystère pas "…" ou une phrase qui fait sens

**Comment by Amustache** [comment]
1 & 2 ok

3 & 4 cf. #14
