### ISSUE TITLE
Remplacer les placeholders par les textes finaux

### ISSUE THREAD

**Issue by ghost** [CLICGameStar/icelan-website-archive#2]
dans les pages suivantes : accueil, infos&planning, contact

**Comment by Amustache** [comment]
![image](https://user-images.githubusercontent.com/5108539/202520388-58b35632-2ab6-4c1b-a058-612a90d97d85.png)
![image](https://user-images.githubusercontent.com/5108539/202520402-09ea34c1-7bf8-446e-87cf-bc752e6d64c7.png)
![image](https://user-images.githubusercontent.com/5108539/202520476-15755f76-f70a-46fd-bf80-e1eae351179d.png)

**Comment by Amustache** [comment]
Done
